<?php
/** op-core:/testcase/sandbox.phtml
 *
 * @created   2022-10-12
 * @version   1.0
 * @package   op-core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

//	...
$args = get_defined_vars();
D($args);

$int  = $args['int'];
$str  = $args['str'];
$bool = $args['bool'];
D($args, $int, $str, $bool);

//	...
return 'Successful';
