<?php
/** op-core:/testcase/template.phtml
 *
 * @created   2022-03-15
 * @version   1.0
 * @package   op-core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

/* @var $args array  */
/* @var $path string */
/* @var $template_path string */
//
$test = $path ?? '(empty)';
$template_path = OP::MetaPath()->Encode($template_path);
?>
<section>
	<h1>template.phtml</h1>
	<p>$template_path=<?= $template_path ?></p>
	<p>$path=<?= $test ?></p>
</section>
<?php
if( $args ){
	if( $test !== 'overwrite' ){
		OP::Notice('Template() is wrong.');
	}
}else{
	if( $test !== '(empty)' ){
		OP::Notice('Template() is wrong.');
	}
}
