<?php
/**
 * core:/Template/Developer/Sendmail.phtml
 *
 * @creation  2016-11-30
 * @version   1.0
 * @package   core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2016 (C) Tomoaki Nagahara All right reserved.
 */

//	Use functions.
include_once(__DIR__.'/Sendmail.inc.php');

//	Timestamp
$time_app	 = Time::Datetime();
$time_std	 = date('Y-m-d H:i:s');
$time_gmt	 = gmdate('Y-m-d H:i:s');
$timestamp = $time_std;

//	GMT
if( $time_std !== $time_gmt ){
	$timestamp .= "<i>(GMT: $time_gmt)</i>";
}

//	Frozen time
if( $time_std !== $time_app ){
	$timestamp .= ", <b>App: $time_app</b>";
}

//	Information
$ip			 = ifset($_SERVER['REMOTE_ADDR']    );
$host		 = gethostbyaddr($ip);
$domain		 = "$host ($ip)";
$ua			 = ifset($_SERVER['HTTP_USER_AGENT']);
$server		 = ifset($_SERVER['HTTP_HOST']      );
$url		 = ifset($_SERVER['REQUEST_URI']    );
$referer	 = ifset($_SERVER['HTTP_REFERER']   );

?>
<div style="font-size:9pt;">
	<table>
		<tr><th> Timestamp	 </th><td> <?= $timestamp ?> <td></tr>
		<tr><th> Domain		 </th><td> <?= $domain ?>	 <td></tr>
		<tr><th> UserAgent	 </th><td> <?= $ua ?>		 <td></tr>
		<tr><th> Server		 </th><td> <?= $server ?>	 <td></tr>
		<tr><th> URL		 </th><td> <?= $url ?>		 <td></tr>
		<tr><th> Referer	 </th><td> <?= $referer ?>	 <td></tr>
	</table>
	<hr/>
	<?php _backtrace($notice['backtrace']) ?>
</div>
